### ISSUE TITLE
Dépendance composer

### ISSUE THREAD

**Issue by gpoma** [24eme/Interface-MongoDB#1]
Bonjour

J'ai voulu installer votre logiciel sur mon ordinateur mais je suis confronté à un problème.
J'ai bien suivi toutes les étapes d'installation du README.

J'ai bien accès à la page où l'on peut ajouter un serveur MongoDB, mais lorsque j'en ajoute un et que je valide, j'ai une page blanche.

Comme je suis un peu geek, je vois dans mon terminal l'erreur suivante :
```
[Thu Sep 24 15:47:43 2020] PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /tmp/Interface-MongoDB/model/model.php on line 509
[Thu Sep 24 15:47:43 2020] PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='/usr/lib64/php') in /tmp/Interface-MongoDB/model/model.php on line 509
[Thu Sep 24 15:47:43 2020] 127.0.0.1:52434 [500]: /index.php?action=getServer - require(): Failed opening required 'vendor/autoload.php' (include_path='/usr/lib64/php') in /tmp/Interface-MongoDB/model/model.php on line 509
```

Je pense qu'il manque quelque chose de composer.
Je n'ai vu ni composer.json ni dossier vendor dans le projet. Peut être que le problème viens de là.

Merci d'avance ;)

**Comment by wincelau** [comment]
J'ai rencontré le même problème :-)

**Comment by rilerss** [comment]
Bonjour,

Effectivement, il y a eu un oubli dans la rédaction du READme, qui est maintenant corrigé.

Vous pouvez à nouveau tester l'installation du projet, en cas de problème n'hésitez pas à le signaler.

Merci de votre remarque, :+1:
